### ISSUE TITLE
Fatal error when Groups component is disabled

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/bp-mpo-activity-filter#1]
I'm seeing a new error in the logs in regards to this plugin when Nouveau is enabled and Groups are disabled. @r-a-y could you take a look to perhaps determine if a pull request is warranted, or if the issue is exclusive to our installation. 

```
[10-Jan-2019 19:55:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function groups_get_groupmeta() in /wordpress/wp-content/plugins/bp-mpo-activity-filter/bp-mpo-activity-filter-bp-functions.php:40
Stack trace:
#0 /wordpress/wp-includes/class-wp-hook.php(286): bp_mpo_activity_filter(true, Object(BP_Activity_Template), Array)
#1 /wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(true, Array)
#2 /wordpress/wp-content/plugins/buddypress/bp-activity/bp-activity-template.php(360): apply_filters('bp_has_activiti...', true, Object(BP_Activity_Template), Array)
#3 /wordpress/wp-content/plugins/buddypress/bp-templates/bp-nouveau/buddypress/activity/activity-loop.php(10): bp_has_activities('page=1')
#4 /wordpress/wp-includes/template.php(688): require_once('/var/www/common...')
#5 /wordpress/wp-content/plugins/buddypress/bp-templates/bp-nouveau/in in /wordpress/wp-content/plugins/bp-mpo-activity-filter/bp-mpo-activity-filter-bp-functions.php on line 40
```

**Comment by r-a-y** [comment]
Yes, this is a problem with BP MPO Activity Filter.

I've put in a hotfix for now, but will send a PR upstream in the next 
day or so.

**Comment by r-a-y** [comment]
PR was merged!
